apiVersion: spark.k8s.io/v1alpha1
kind: SparkCluster
metadata:
  labels:
    app: user1-cluster
  name: user1-cluster
spec:
  # Add fields here
  gitRepo: https://github.com/owhileo/FBDP.git
  clusterPrefix: user1-cluster
  slaveNum: 1
  pvcEnable: False
  datasets: ["dataset1"]
  nfs: False 
  # ports:
  #   - port: 9000
  #     name: hdfs

  # resources:
  #   limits:
  #     cpu: "2"
  #     memory: "2000Mi"
  #   requests:
  #     cpu: "1"
  #     memory: "1500Mi"

  # nfs: True

